Repository Softwaret/kpdf, pull requests merged in 2020-07, with the labels that each got.

#6 Feature/js 5 bump kodein version
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  resources/application.conf
  src/Application.kt
  src/com/softwaret/kpdf/Application.kt
  src/com/softwaret/kpdf/controller/ControllerModule.kt
  src/com/softwaret/kpdf/controller/hello/HelloController.kt
  src/com/softwaret/kpdf/controller/hello/HelloControllerImpl.kt
  src/com/softwaret/kpdf/util/Di.kt
Labels: feature, help wanted

#11 Feature/js 9 register
  src/com/softwaret/kpdf/Application.kt
  src/com/softwaret/kpdf/controller/ControllerModule.kt
  src/com/softwaret/kpdf/controller/base/BaseController.kt
  src/com/softwaret/kpdf/controller/login/LoginControllerImpl.kt
  src/com/softwaret/kpdf/controller/register/RegisterController.kt
  src/com/softwaret/kpdf/controller/register/RegisterControllerImpl.kt
  src/com/softwaret/kpdf/db/H2Db.kt
  src/com/softwaret/kpdf/db/tables/User.kt
  src/com/softwaret/kpdf/interactor/InteractorModule.kt
  src/com/softwaret/kpdf/interactor/login/LoginInteractorImpl.kt
  src/com/softwaret/kpdf/interactor/register/RegisterInteractor.kt
  src/com/softwaret/kpdf/interactor/register/RegisterInteractorImpl.kt
  src/com/softwaret/kpdf/mapper/UserTileMapper.kt
  src/com/softwaret/kpdf/model/UserTile.kt
  src/com/softwaret/kpdf/response/ResponseModule.kt
  src/com/softwaret/kpdf/response/error/ErrorType.kt
  src/com/softwaret/kpdf/response/error/factory/ErrorFactory.kt
  src/com/softwaret/kpdf/response/error/factory/ErrorFactoryImpl.kt
  src/com/softwaret/kpdf/response/success/RegisterResponse.kt
  src/com/softwaret/kpdf/routing/Locations.kt
  src/com/softwaret/kpdf/routing/routes/Register.kt
  src/com/softwaret/kpdf/service/ServiceModule.kt
  src/com/softwaret/kpdf/service/user/BaseUserService.kt
  src/com/softwaret/kpdf/service/user/LoginUserService.kt
  src/com/softwaret/kpdf/service/user/RegisterUserService.kt
  src/com/softwaret/kpdf/service/user/UserServiceImpl.kt
  src/com/softwaret/kpdf/util/BodyParameters.kt
Labels: feature, help wanted

#15 Refactor response creation
  src/com/softwaret/kpdf/application/Application.kt
  src/com/softwaret/kpdf/controller/ControllerModule.kt
  src/com/softwaret/kpdf/controller/base/BaseController.kt
  src/com/softwaret/kpdf/controller/login/LoginControllerImpl.kt
  src/com/softwaret/kpdf/controller/register/RegisterControllerImpl.kt
  src/com/softwaret/kpdf/response/Response.kt
  src/com/softwaret/kpdf/response/ResponseBody.kt
  src/com/softwaret/kpdf/response/ResponseModule.kt
  src/com/softwaret/kpdf/response/error/Error.kt
  src/com/softwaret/kpdf/response/error/ErrorData.kt
  src/com/softwaret/kpdf/response/error/ErrorResponseBody.kt
  src/com/softwaret/kpdf/response/error/ErrorType.kt
  src/com/softwaret/kpdf/response/error/factory/ErrorFactory.kt
  src/com/softwaret/kpdf/response/error/factory/ErrorFactoryImpl.kt
  src/com/softwaret/kpdf/response/success/LoginResponse.kt
  src/com/softwaret/kpdf/response/success/LoginResponseBody.kt
  src/com/softwaret/kpdf/response/success/RegisterResponse.kt
  src/com/softwaret/kpdf/response/success/RegisterResponseBody.kt
  src/com/softwaret/kpdf/routing/Locations.kt
  src/com/softwaret/kpdf/routing/routes/Login.kt
  src/com/softwaret/kpdf/routing/routes/Register.kt
  src/com/softwaret/kpdf/util/BodyParameter.kt
  src/com/softwaret/kpdf/util/BodyParameters.kt
  src/com/softwaret/kpdf/util/extension/Di.kt
  src/com/softwaret/kpdf/util/extension/ParametersExtension.kt
  src/com/softwaret/kpdf/util/extension/Respond.kt
Labels: enhancement, feature

#17 Create README.md
  README.md
Labels: documentation, enhancement
